### ISSUE TITLE
Text attribute error

### ISSUE THREAD

**Issue by adinesia** [parth1902/Scrape-FBref-data#2]
Hi, I got this error massage when scrapping Brazilian and Argentina stats: AttributeError: 'NoneType' object has no attribute 'text'
Could you please help. Thanks

**Comment by matze298** [comment]
The error occurs because the scraper tries to find values that don't exist for the Brazilian & Argentinian leagues.
From the Readme: "The scraper won't work for those leagues which have other columns compared to the top 5 leagues."

**Comment by MartinHolthe** [comment]
Hi, I actually got the same issue as stated above - for all the top 5 leagues: AttributeError: 'NoneType' object has no attribute 'text'. The code has been working perfectly for some months, but it suddenly stopped working as of today... Would appreciate some help. Thanks

**Comment by MartinHolthe** [comment]
The solution can be located here: https://stackoverflow.com/questions/66517625/attributeerror-nonetype-object-has-no-attribute-text-beautifulshop

**Comment by Lilvim** [comment]
The solution is not working I tried what they said and it doesn't work. It's exactly the same problem than before
Can I get a hint ?

**Comment by parth1902** [comment]
Removed the problem! Added a link to a colab notebook as well, please refer to it if needed.
