### ISSUE TITLE
Player Table located in index #2

### ISSUE THREAD

**Issue by a00822504** [parth1902/Scrape-FBref-data#3]
Hello Mr. Parth 1902,

First of all thank you for this great peace of code, really helpful.

I noticed that when scrapping the data, your players table is "player_table = all_tables[1]".

I noticed that the output of this table is the Opponent Stats table from FBref and not the players' table. The quick and easy fix would be:

player_table = all_tables[2].

Hope this helps.

Cheers

**Comment by QuantQB8** [comment]
Yes!

**Comment by parth1902** [comment]
Made the changes! Added a link to a colab notebook as well, please refer to it if needed.
